name: Build/Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build
        run: |
          npm install
          npm run make
        if: matrix.os == 'macos-latest'

      # - name: Build
      #   run: |
      #     npm install
      #     npm run make-macos-x64
      #   if: matrix.os == 'macos-latest'

      # - name: Build
      #   run: |
      #     npm install
      #     npm run make-linux-x64-deb
      #   if: matrix.os == 'ubuntu-latest'

      # - name: Build
      #   run: |
      #     npm install
      #     npm run make-windows-x64
      #   if: matrix.os == 'windows-latest'

      - name: List Files
        run: |
          npm install -g tree-cli
          tree --ignore 'node_modules/,.git' -l 8
