name: Test Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test-release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create Release
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            core.startGroup('context output')
            core.info(JSON.stringify(context, null, 2))
            core.endGroup()

            console.log('context.repo', context.repo)

            // Based on: https://github.com/actions/create-release/blob/main/src/create-release.js
            const releaseName = 'test-release-name'
            const tagName = 'test-release-tag'

            // Create a release
            // API Documentation: https://docs.github.com/en/rest/reference/repos#create-a-release
            const createReleaseResponse = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              name: releaseName,
              body: null,
              draft: true,
              prerelease: false,
              target_commitish: context.sha
            });
